import { database } from "./firebase.js";

import {
    ref,
    get
} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";

const logo = new Image();
logo.src = "images/logo.png";
window.downloadReport = async function (appointmentId) {
    const snapshot = await get(ref(database, "appointments/" + appointmentId));

if (!snapshot.exists()) {

    alert("Appointment not found.");

    return;

}

const appointment = snapshot.val();

const patientName = appointment.patientName;
const patientEmail = appointment.patientEmail;
const laboratory = appointment.laboratory;
const test = appointment.test;
const date = appointment.date;
const result = appointment.result;

    const { jsPDF } = window.jspdf;

    const doc = new jsPDF();

    // ===== HEADER =====

// Add logo
doc.addImage(logo, "PNG", 65, 15, 80, 50);

// Report title
doc.setFont("helvetica", "bold");
doc.setFontSize(16);
doc.text("LABORATORY REPORT", 105, 75, { align: "center" });

doc.line(20, 80, 190, 80);

    // ===== PATIENT DETAILS =====
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");

    doc.text("Patient Name:", 20, 95);
    doc.setFont("helvetica", "normal");
    doc.text(patientName, 70, 95);

    doc.setFont("helvetica", "bold");
    doc.text("Email:", 20, 105);
    doc.setFont("helvetica", "normal");
    doc.text(patientEmail, 70, 105);

    doc.setFont("helvetica", "bold");
    doc.text("Laboratory:", 20, 115);
    doc.setFont("helvetica", "normal");
    doc.text(laboratory, 70, 115);

    doc.setFont("helvetica", "bold");
    doc.text("Test:", 20, 125);
    doc.setFont("helvetica", "normal");
    doc.text(test, 70, 125);

    doc.setFont("helvetica", "bold");
    doc.text("Date:", 20, 135);
    doc.setFont("helvetica", "normal");
    doc.text(date, 70, 135);

    // ===== RESULTS =====
    doc.line(20, 145, 190, 145);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("LABORATORY RESULTS", 20, 160);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);

    const lines = doc.splitTextToSize(result, 165);
    doc.text(lines, 20, 172);

    // ===== STATUS =====
    let y = 185 + (lines.length * 6);

    doc.line(20, y, 190, y);

    y += 12;

    doc.setFont("helvetica", "bold");
    doc.text("Status:", 20, y);

    doc.setFont("helvetica", "normal");
    doc.text("Completed", 55, y);

    // ===== REPORT ID =====
    y += 12;

    doc.setFont("helvetica", "bold");
    doc.text("Report ID:", 20, y);

    doc.setFont("helvetica", "normal");
    doc.text(
        "LP-" + Math.floor(Math.random() * 1000000),
        55,
        y
    );

    // ===== SIGNATURE =====
    y += 25;

    doc.line(120, y, 185, y);

    y += 6;

    doc.text("Laboratory Signature", 125, y);

    // ===== FOOTER =====
    doc.setFontSize(10);

    doc.text(
        "Generated by LabPulse Health Laboratory Management System",
        105,
        285,
        { align: "center" }
    );

    doc.save("LabPulse-Laboratory-Report.pdf");

};