window.downloadReport = function (
    patientName,
    patientEmail,
    laboratory,
    test,
    date,
    result
) {

    const { jsPDF } = window.jspdf;

    const doc = new jsPDF();

    // ===== HEADER =====
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("LabPulse Health", 105, 20, { align: "center" });

    doc.setFontSize(16);
    doc.text("LABORATORY REPORT", 105, 30, { align: "center" });

    doc.line(20, 35, 190, 35);

    // ===== PATIENT DETAILS =====
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");

    doc.text("Patient Name:", 20, 50);
    doc.setFont("helvetica", "normal");
    doc.text(patientName, 70, 50);

    doc.setFont("helvetica", "bold");
    doc.text("Email:", 20, 60);
    doc.setFont("helvetica", "normal");
    doc.text(patientEmail, 70, 60);

    doc.setFont("helvetica", "bold");
    doc.text("Laboratory:", 20, 70);
    doc.setFont("helvetica", "normal");
    doc.text(laboratory, 70, 70);

    doc.setFont("helvetica", "bold");
    doc.text("Test:", 20, 80);
    doc.setFont("helvetica", "normal");
    doc.text(test, 70, 80);

    doc.setFont("helvetica", "bold");
    doc.text("Date:", 20, 90);
    doc.setFont("helvetica", "normal");
    doc.text(date, 70, 90);

    // ===== RESULTS =====
    doc.line(20, 100, 190, 100);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("LABORATORY RESULTS", 20, 110);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);

    const lines = doc.splitTextToSize(result, 165);
    doc.text(lines, 20, 120);

    // ===== STATUS =====
    let y = 130 + (lines.length * 6);

    doc.line(20, y, 190, y);

    y += 12;

    doc.setFont("helvetica", "bold");
    doc.text("Status:", 20, y);

    doc.setFont("helvetica", "normal");
    doc.text("Completed", 55, y);

    // ===== REPORT ID =====
    y += 12;

    doc.setFont("helvetica", "bold");
    doc.text("Report ID:", 20, y);

    doc.setFont("helvetica", "normal");
    doc.text(
        "LP-" + Math.floor(Math.random() * 1000000),
        55,
        y
    );

    // ===== SIGNATURE =====
    y += 25;

    doc.line(120, y, 185, y);

    y += 6;

    doc.text("Laboratory Signature", 125, y);

    // ===== FOOTER =====
    doc.setFontSize(10);

    doc.text(
        "Generated by LabPulse Health Laboratory Management System",
        105,
        285,
        { align: "center" }
    );

    doc.save("LabPulse-Laboratory-Report.pdf");

};